function formatScaleDisconnect(sc){return sc.lastDisconnect?.summary||sc.lastDisconnectReasonName||__WEBUI_TEXT__("diagnostic.none_2")}
function formatScaleCommandFailure(c){return c?.summary||__WEBUI_TEXT__("diagnostic.none_3")}
'use strict';import*as R from'./runtime.js?v=__FW_ASSET_TAG__';const $=R.$;let ready=false;const flags=(o,...keys)=>keys.map(k=>k+'='+(o[k]?'1':'0')).join(' ');function fmtTaskPct(n){return Number.isFinite(n)?n.toFixed(1)+'%':'—'}function applyTaskProfiler(t){const T=$('hTaskState'),E=$('hTaskElapsed'),B=$('taskTableBody'),H=$('taskTableHint'),A=$('taskProfilerStartButton'),P=$('taskProfilerStopButton'),own=!!R.webUiOwner;if(!t||typeof t.state!='string'){if(T)T.textContent=__WEBUI_TEXT__("diagnostic.unknown");if(E)E.textContent=__WEBUI_TEXT__("diagnostic.unknown");if(B)B.replaceChildren()
;if(H)H.textContent='';if(A)A.disabled=!own;if(P)P.disabled=true;return}const run=t.state==='running';if(T){let s={never:__WEBUI_TEXT__("diagnostic.idle"),running:__WEBUI_TEXT__("diagnostic.running"),stopped:__WEBUI_TEXT__("diagnostic.stopped"),failed:__WEBUI_TEXT__("diagnostic.failed")}[t.state]||t.state;if(t.stopReason&&(t.state==='failed'&&t.stopReason!=='none'||t.state==='stopped'&&t.stopReason==='timeout'))s+=' ('+t.stopReason+')';T.textContent=s}if(E)E.textContent=['running','stopped','failed'].includes(t.state)?Math.floor((t.elapsedMs||0)/1e3)+__WEBUI_TEXT__("diagnostic.s"):__WEBUI_TEXT__("diagnostic.unknown");if(A)A.disabled=run||!own
;if(P)P.disabled=!run||!own;if(B){B.replaceChildren();for(const r of t.rows||[]){const tr=document.createElement('tr');[r.name||'—',[0,1].includes(r.core)?r.core:'—',fmtTaskPct(r.currentCpuPct),fmtTaskPct(r.averageCpuPct),r.stackMinWords<4294967295?r.stackMinWords??'—':'—'].forEach(c=>{const td=document.createElement('td');td.textContent=c;tr.appendChild(td)});B.appendChild(tr)}}if(H){const p=t.truncated?[__WEBUI_TEXT__("diagnostic.list_truncated")]:[];for(const[label,value]of[[__WEBUI_TEXT__("diagnostic.other_now"),t.unreportedCurrentCpuPct],[__WEBUI_TEXT__("diagnostic.other_avg"),t.unreportedAverageCpuPct],[__WEBUI_TEXT__("diagnostic.total_now"),t.currentTotalCpuPct]])if(Number.isFinite(value)&&(label==='Total now'||value>.05))p.push(label+' '+fmtTaskPct(value));H.textContent=p.join(__WEBUI_TEXT__("diagnostic.symbol_3"))}}function applyDiagnosticGuards(s){const g=s&&s.guards;if(!g)return
;const live=!!s.machineRunning,b=!!g.bbwEnabled,ns=g.noScale||{},atm=g.atm||{},slow=g.slowExtraction||{},fast=g.fastExtraction||{},touch=g.accidentalTouch||{},cup=g.cupProtection||{},t=(i,v)=>{const e=$(i);if(e)e.textContent=v||__WEBUI_TEXT__("diagnostic.unknown")};t('dGuardNoScaleUser',R.formatNoScaleGuard(b?{enabled:!!ns.enabled,armed:!!ns.armed}:{enabled:false}));t('dGuardNoScaleRaw',flags(ns,'enabled','armed','hold','scaleWasAvailable'))
;t('dGuardAtmUser',R.formatAtmGuard({atmEnabled:b&&!!atm.enabled,atmEnforced:live&&!!atm.enforced,atmArmed:live&&!!atm.armed,atmRemainingMs:atm.remainingMs}));t('dGuardAtmRaw',flags(atm,'enabled','armed','enforced')+__WEBUI_TEXT__("diagnostic.remainingms")+(atm.remainingMs||0));t('dGuardSlowUser',R.formatSlowExtractionGuard({guardEnabled:b&&!!slow.enabled,extended:live&&!!slow.extended,goal:slow.activeStopWeightG,inShot:live}))
;t('dGuardSlowRaw',flags(slow,'enabled','extended','targetReachedEarly')+__WEBUI_TEXT__("diagnostic.activestopweightg")+(typeof slow.activeStopWeightG==='number'?slow.activeStopWeightG.toFixed(1):__WEBUI_TEXT__("diagnostic.0_0")));t('dGuardFastUser',R.formatExtractionGuard({guardEnabled:b&&!!fast.enabled,extended:live&&!!fast.extended,goal:fast.activeStopWeightG,minBbwBrewRemainingMs:fast.minBbwBrewTimeRemainingMs,inShot:live}))
;t('dGuardFastRaw',flags(fast,'enabled','extended','targetReachedEarly')+__WEBUI_TEXT__("diagnostic.activestopweightg")+(typeof fast.activeStopWeightG==='number'?fast.activeStopWeightG.toFixed(1):__WEBUI_TEXT__("diagnostic.0_0"))+__WEBUI_TEXT__("diagnostic.minbbwbrewtimeremainingms")+(fast.minBbwBrewTimeRemainingMs||0));t('dGuardTouchUser',R.formatAccidentalTouch({enabled:b&&!!touch.enabled,holding:live&&!!touch.holding,inShot:live}))
;t('dGuardTouchRaw',flags(touch,'enabled','holding')+__WEBUI_TEXT__("diagnostic.phase")+(touch.phase||__WEBUI_TEXT__("diagnostic.startup"))+__WEBUI_TEXT__("diagnostic.class")+(touch.class||__WEBUI_TEXT__("diagnostic.ok"))+__WEBUI_TEXT__("diagnostic.pendingcount")+(touch.pendingCount||0));t('dGuardCupUser',R.formatCupProtection({enabled:b&&!!cup.enabled,requireCupToStart:!!cup.requireCupToStart,stopIfRemoved:!!cup.stopIfRemoved,present:!!cup.present,scaleUsable:!!g.scaleUsable,inShot:live,aborted:!live&&!!g.lastShotCupRemoved}))
;t('dGuardCupRaw',flags(cup,'enabled','stopIfRemoved','requireCupToStart','present','startHold','removedPending','bbwProtectionActive','bbwProtectionEnded'))}async function exportDebugData(){const btn=$('exportDebugDataButton');btn.disabled=true;R.message(__WEBUI_TEXT__("diagnostic.exporting"));try{
const data=await R.api('/api/v1/debug/export',{timeoutMs:3e4});if(!data||typeof data.exportSchemaVersion!=='number')throw new Error(__WEBUI_TEXT__("diagnostic.invalid_export"));const a=document.createElement('a'),boot=typeof data.bootId==='number'?data.bootId:R.bootId||0;a.href=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));a.download='shotstopper-debug-boot'+boot+'-'+(new Date).toISOString().replace(/[:.]/g,'-').slice(0,19)+'.json';document.body.appendChild(a);a.click();a.remove()
;R.message(__WEBUI_TEXT__("diagnostic.ok"),'ok');R.noteReachOk()}catch(e){R.message(R.formatCommandError(__WEBUI_TEXT__("diagnostic.export_failed"),e),'error');R.noteReachFail(e)}finally{btn.disabled=false}}export function applyStatus(s){R.applyDiagnosticStatus(s);if($('serialLogLevel'))$('serialLogLevel').value=(s&&s.config||{}).serialLogLevel||'none';if(!s||!(s.adminUnlocked||s.diagnosticPublic))return;const sc=s.scale||{};$('hLastDisconnect').textContent=formatScaleDisconnect(sc);$('hScaleCommandFailure').textContent=formatScaleCommandFailure(sc.lastCommandFailure);applyDiagnosticGuards(s);applyTaskProfiler(s.tasks);const b=$('hResetHistory');if(b){b.replaceChildren();for(const e of s.resetHistory||[]){const r=b.insertRow()
;r.insertCell().textContent=e.reason;r.insertCell().textContent=R.formatUptime(e.uptimeMs)}}}export function init(){if(ready)return;ready=true;R.registerViewStatus('diagnostic',applyStatus);const lock=$('diagnosticLockPanel'),controls=$('diagnosticControls');if(lock)lock.remove();if(controls)controls.classList.remove('hidden');$('serialLogLevel').onchange=()=>R.command('/api/v1/config',R.withBaseRev({serialLogLevel:$('serialLogLevel').value}))
;$('ringRetainLogLevel').onchange=()=>R.command('/api/v1/config',R.withBaseRev({ringRetainLogLevel:$('ringRetainLogLevel').value||'none'}));$('logFilter').onchange=R.renderLog;$('logLevelFilter').onchange=R.renderLog;$('copyLogButton').onclick=()=>navigator.clipboard&&navigator.clipboard.writeText($('log').value);$('clearLogButton').onclick=()=>R.clearLogView();$('exportDebugDataButton').onclick=()=>exportDebugData()
;$('clearResetHistoryButton').onclick=()=>confirm(__WEBUI_TEXT__("diagnostic.clear_resets"))&&R.command('/api/v1/diagnostic/reset-history',{confirm:'CLEAR_RESET_HISTORY'});$('taskProfilerStartButton').onclick=()=>R.command('/api/v1/diagnostic/profiler',{enabled:true});$('taskProfilerStopButton').onclick=()=>R.command('/api/v1/diagnostic/profiler',{enabled:false})}export function activate(){}
