#!/bin/sh
# Generates src/ShotStopperVersion.h.
#
# Usage: gen_version.sh [board_arch]
#
# board_arch is the OTA compatibility key (n8r4 / n16r8). It is baked into the
# image tag so the controller can refuse a binary built for the other board.
# Callers that do not produce a flashable image (host tests) may omit it; the
# resulting "unknown" arch never matches a real controller, which is the safe
# outcome.
set -eu

root=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
version_file="$root/VERSION"
output="$root/src/ShotStopperVersion.h"

arch=${1:-unknown}
case "$arch" in
  n8r4|n16r8|unknown) ;;
  *)
    echo "Invalid board arch: '$arch' (expected n8r4, n16r8 or unknown)" >&2
    exit 1
    ;;
esac

ver=$(tr -d '[:space:]' < "$version_file")
case "$ver" in
  *[!0-9.]*|""|*.*.*.*)
    echo "Invalid VERSION: '$ver' (expected MAJOR.MINOR.PATCH)" >&2
    exit 1
    ;;
esac

major=${ver%%.*}
rest=${ver#*.}
minor=${rest%%.*}
patch=${rest#*.}

if [ -z "$major" ] || [ -z "$minor" ] || [ -z "$patch" ]; then
  echo "Invalid VERSION: '$ver' (expected MAJOR.MINOR.PATCH)" >&2
  exit 1
fi

if [ "$major" -gt 255 ] || [ "$minor" -gt 255 ] || [ "$patch" -gt 65535 ]; then
  echo "Invalid VERSION: '$ver' (major/minor <= 255, patch <= 65535)" >&2
  exit 1
fi

packed=$(( (major << 24) | (minor << 16) | patch ))

if git -C "$root" rev-parse --is-inside-work-tree >/dev/null 2>&1; then
  sha=$(git -C "$root" rev-parse --short=7 HEAD)
  dirty=""
  if ! git -C "$root" diff --quiet || ! git -C "$root" diff --cached --quiet; then
    dirty="-dirty"
  fi
else
  sha="unknown"
  dirty=""
fi

build_id="${ver}+${sha}${dirty}"

cat > "$output" <<EOF
#pragma once

// Generated by scripts/gen_version.sh — do not edit.

#include <stdint.h>

#define FW_VERSION_STRING "${build_id}"
#define FW_BOARD_ARCH_STRING "${arch}"
#define FW_VERSION_PACKED_STRING "${packed}"

// Contiguous marker embedded in every flashable image. The OTA verifier scans
// an uploaded binary for this literal to prove the file is a Shot Stopper build
// for this exact board before it may become the boot image. Keep the field
// order and the "|END" terminator in sync with ShotStopperOta.cpp.
#define FW_IMAGE_TAG_STRING                                     \\
  "SHOTSTOPPER_FW_TAG_V1|arch=" FW_BOARD_ARCH_STRING            \\
  "|ver=" FW_VERSION_STRING                                     \\
  "|packed=" FW_VERSION_PACKED_STRING "|END"

namespace shotstopper {

constexpr char FW_VERSION[] = FW_VERSION_STRING;
constexpr char FW_BOARD_ARCH[] = FW_BOARD_ARCH_STRING;
constexpr uint32_t FW_VERSION_PACKED = 0x$(printf '%08x' "$packed")U;

}  // namespace shotstopper
EOF

echo "Generated $output ($build_id, arch=$arch)"
