#!/usr/bin/env python3
"""Generate the bounded firmware time-zone table from a local IANA release."""

import argparse
import hashlib
import pathlib
import struct
import subprocess
import tarfile
import tempfile

SOURCE_SHA256 = "0cb2aa8e333c3dc049badc42a0c61f21987b8cd44e107fa900bad764aacc7767"
START = 1735689600  # 2025-01-01T00:00:00Z
END = 4102444800    # 2100-01-01T00:00:00Z
SOURCES = ("africa", "antarctica", "asia", "australasia", "europe",
           "northamerica", "southamerica", "etcetera", "backward")


def transitions(path):
    data = path.read_bytes()
    if data[:4] != b"TZif" or data[4:5] not in (b"2", b"3", b"4"):
        raise ValueError(f"unsupported TZif: {path}")
    counts = struct.unpack(">6I", data[20:44])
    first_size = 44 + counts[3] * 5 + counts[4] * 6 + counts[5] + counts[2] * 8 + counts[1] + counts[0]
    counts = struct.unpack(">6I", data[first_size + 20:first_size + 44])
    pos = first_size + 44
    instants = struct.unpack(f">{counts[3]}q", data[pos:pos + counts[3] * 8])
    pos += counts[3] * 8
    indices = data[pos:pos + counts[3]]
    pos += counts[3]
    offsets = [struct.unpack(">l", data[pos + i * 6:pos + i * 6 + 4])[0]
               for i in range(counts[4])]
    rows = [(instant, offsets[indices[i]]) for i, instant in enumerate(instants)
            if START <= instant < END]
    if not rows or rows[0][0] != START:
        raise ValueError(f"missing range-start offset: {path}")
    result = []
    for instant, offset in rows:
        if instant % 60 or offset % 60 or not -32768 <= offset // 60 <= 32767:
            raise ValueError(f"subminute or out-of-range offset: {path}")
        result.append(((instant - START) // 60, offset // 60))
    return tuple(result)


def generate(source, output):
    if hashlib.sha256(source.read_bytes()).hexdigest() != SOURCE_SHA256:
        raise ValueError("IANA tzdata archive SHA-256 does not match 2026d")
    with tempfile.TemporaryDirectory() as temp:
        root = pathlib.Path(temp)
        with tarfile.open(source, "r:gz") as archive:
            for name in SOURCES + ("version", "LICENSE"):
                member = archive.extractfile(name)
                if member is None:
                    raise ValueError(f"missing IANA source: {name}")
                (root / name).write_bytes(member.read())
        if (root / "version").read_text().strip() != "2026d":
            raise ValueError("unexpected IANA release")
        zoneinfo = root / "zoneinfo"
        zoneinfo.mkdir()
        subprocess.run(["zic", "-d", str(zoneinfo), "-b", "fat", "-r",
                        f"@{START}/@{END}", *(str(root / name) for name in SOURCES)],
                       check=True)
        names = sorted(p.relative_to(zoneinfo).as_posix() for p in zoneinfo.rglob("*")
                       if p.is_file() and p.read_bytes()[:4] == b"TZif")
        catalog = []
        all_rows = []
        reuse = {}
        for name in names:
            rows = transitions(zoneinfo / name)
            if rows not in reuse:
                reuse[rows] = (len(all_rows), len(rows))
                all_rows.extend(rows)
            catalog.append((name, *reuse[rows]))
        if len(all_rows) >= 65536 or any(len(name) >= 64 for name in names):
            raise ValueError("catalog exceeds firmware bounds")
        lines = ["// Generated by scripts/generate_timezones.py from IANA tzdata2026d.",
                 f"// Source SHA-256: {SOURCE_SHA256}",
                 "// IANA tzdata license: public-domain database; see upstream LICENSE.",
                 "#pragma once", "#include <stdint.h>",
                 "namespace shotstopper::tzdb {",
                 "inline constexpr uint32_t kStartUtc = 1735689600U;",
                 "inline constexpr uint32_t kEndUtc = 4102444800U;",
                 "inline constexpr const char *kVersion = \"2026d\";",
                 "struct __attribute__((packed)) Transition { uint32_t minute; int16_t offset; };",
                 "struct Zone { const char *id; uint16_t first; uint16_t count; };",
                 "inline constexpr Transition kTransitions[] = {"]
        lines.extend(f"  {{{minute}U, {offset}}}," for minute, offset in all_rows)
        lines += ["};", "inline constexpr Zone kZones[] = {"]
        lines.extend(f'  {{"{name}", {first}, {count}}},' for name, first, count in catalog)
        lines += ["};", "inline constexpr uint16_t kZoneCount = sizeof(kZones) / sizeof(kZones[0]);",
                  "}  // namespace shotstopper::tzdb", ""]
        output.write_text("\n".join(lines))
        print(f"{len(names)} IDs, {len(reuse)} unique schedules, {len(all_rows)} transitions")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("archive", type=pathlib.Path)
    parser.add_argument("output", type=pathlib.Path)
    args = parser.parse_args()
    generate(args.archive, args.output)
