'use strict';import*as R from'/js/runtime.js?v=__FW_ASSET_TAG__';R.paintTheme(R.themeMode());document.addEventListener('change',e=>{if(e.target&&e.target.id==='uiTheme')R.paintTheme(e.target.value)});const diagnosticNav=document.querySelector('[data-route="/diagnostic"]')
;if(diagnosticNav)diagnosticNav.classList.add('hidden');const assetQuery=new URL(import.meta.url).search;const jsMods=new Map;const htmlLoaded=new Set(['home']);const viewLoads=new Map;const SECONDARY=new Set(['stats','history','diagnostic','admin']);let secondaryViews=null;let logTimer=0;let shotsTimer=0;let historyTimer=0;let routeSeq=0;let activeView='';const ROUTES={'/':'home','/settings':'settings','/stats':'stats','/history':'history','/admin':'admin','/diagnostic':'diagnostic','/log':'diagnostic'}
;function knownPath(pathname){const p=(pathname||'/').replace(/\/+$/,'')||'/';return Object.prototype.hasOwnProperty.call(ROUTES,p)?p:null}function viewToPath(view){for(const[p,v]of Object.entries(ROUTES)){if(v===view)return p}return'/'}async function loadPartial(name){const response=await fetch('/partials/'+name+'.html'+assetQuery);if(!response.ok)throw new Error(__WEBUI_TEXT__("shell.failed_to_load_view_markup"));return response.text()}async function ensureView(name){if(jsMods.has(name)&&htmlLoaded.has(name))return jsMods.get(name);if(viewLoads.has(name))return viewLoads.get(name);const load=(async()=>{const section=document.getElementById('view-'+name);if(!section)throw new Error(__WEBUI_TEXT__("shell.missing_view_section")+name);if(name==='home'){if(__homeModule.init)__homeModule.init();jsMods.set('home',__homeModule);return __homeModule}const markup=htmlLoaded.has(name)?null:loadPartial(name),module=SECONDARY.has(name)?(secondaryViews||(secondaryViews=import('/js/secondary.js'+assetQuery).then(sec=>sec.views).catch(e=>{secondaryViews=null;throw e}))).then(views=>views[name]):import('/js/'+name+'.js'+assetQuery);
const[html,mod]=await Promise.all([markup,module]);if(!mod)throw new Error(__WEBUI_TEXT__("shell.missing_secondary_view")+name);if(html!==null){section.innerHTML=html;htmlLoaded.add(name)}if(mod.init)mod.init();jsMods.set(name,mod);return mod})();viewLoads.set(name,load);try{return await load}finally{viewLoads.delete(name)}}R.setEnsureViewHook(ensureView);function stopExtraPolls(){clearInterval(logTimer);clearInterval(shotsTimer);clearInterval(historyTimer);logTimer=shotsTimer=historyTimer=0}function startView(name,seq=routeSeq){return R.withPollGate(async()=>{
if(!R.webUiPollingActive()||name!==activeView||seq!==routeSeq)return false;
stopExtraPolls();let ok=false;
if(name==='diagnostic'){try{const access=await R.api('/api/v1/status/home');if(seq!==routeSeq)return false;const visible=access&&access.diagnosticPageVisible===true;if(diagnosticNav)diagnosticNav.classList.toggle('hidden',!visible||R.compatibilityModeOn())}catch(_){}}if(seq!==routeSeq)return false;
if(name==='home'||name==='settings'||name==='admin'||name==='diagnostic'){ok=await R.loadStatus();R.armStatusTimer()}
if(name!==activeView||seq!==routeSeq)return false;
if(name==='diagnostic'){if(ok)ok=await R.loadLog();logTimer=setInterval(()=>{if(!document.hidden)R.refreshLog()},4e3)}
if(name==='stats'||name==='history'){const stats=name==='stats';ok=await(stats?R.loadShots():R.loadHistory());if(name===activeView&&seq===routeSeq){const timer=setInterval(()=>{if(!document.hidden)(stats?R.refreshShots:R.refreshHistory)()},2e4);if(stats)shotsTimer=timer;else historyTimer=timer}}
return ok;
})}async function renderRoute(pathname){const seq=++routeSeq,boot=R.showPageBoot();R.stopViewPolls();const known=knownPath(pathname);let view='home';let target='/';if(known){view=ROUTES[known];target=known}
if(R.compatibilityModeOn()&&view!=='admin'&&view!=='diagnostic'){view='admin';target='/admin'}if(location.pathname!==target)history.replaceState({},'',target);activeView=view;const ready=ensureView(view).then(()=>{if(seq!==routeSeq)return;document.querySelectorAll('.view').forEach(el=>el.classList.toggle('hidden',el.dataset.view!==view));document.querySelectorAll('.pageNav a').forEach(a=>a.classList.toggle('active',a.getAttribute('data-route')===viewToPath(view)))});R.setActiveView(view,ready)
;try{const[,ok]=await Promise.all([ready,startView(view)]);if(seq!==routeSeq)return;if(ok)R.hideHomeBoot(boot);else if(R.webUiPollingActive())R.message(__WEBUI_TEXT__("shell.unable_to_load_view"),'error')}catch(e){if(seq===routeSeq)R.message(e&&e.message?e.message:__WEBUI_TEXT__("shell.unable_to_load_view"),'error')}}function setNav(open){document.body.classList.toggle('navOpen',!!open);const btn=document.getElementById('navToggle');if(btn){btn.type='button';btn.setAttribute('aria-expanded',open?'true':'false')}}function navigate(path){const known=knownPath(path)
;const target=known?known:'/';setNav(false);if(location.pathname!==target)history.pushState({},'',target);renderRoute(target)}R.setViewPollHooks({stop:stopExtraPolls,start:()=>renderRoute(location.pathname),route:pathname=>renderRoute(pathname||location.pathname)});document.querySelectorAll('a[data-route]').forEach(a=>{a.addEventListener('click',e=>{e.preventDefault();navigate(a.getAttribute('data-route')||'/')})})
;const pageNav=document.querySelector('.pageNav');if(pageNav){pageNav.setAttribute('aria-label',__WEBUI_TEXT__("shell.primary"));pageNav.addEventListener('click',e=>{if(e.target===pageNav)setNav(false)})}const msgEl=document.getElementById('message');if(msgEl){msgEl.setAttribute('role','status');msgEl.setAttribute('aria-live','polite')}setNav(false);const navToggle=document.getElementById('navToggle');if(navToggle){navToggle.addEventListener('click',()=>{setNav(!document.body.classList.contains('navOpen'))})}
if(window.matchMedia){const desktopNav=window.matchMedia('(min-width: 700px)');const closeDesktopNav=e=>{if(e.matches)setNav(false)};if(desktopNav.addEventListener){desktopNav.addEventListener('change',closeDesktopNav)}else if(desktopNav.addListener){desktopNav.addListener(closeDesktopNav)}}document.addEventListener('keydown',e=>{if(e.key==='Escape')setNav(false)});window.addEventListener('popstate',()=>{setNav(false);renderRoute(location.pathname)})
;document.addEventListener('visibilitychange',()=>{R.noteWebUiPowerActivity();document.hidden?R.stopViewPolls():startView(activeView)});document.addEventListener('wheel',R.noteWebUiInteraction,{capture:true,passive:true});document.addEventListener('touchmove',R.noteWebUiInteraction,{capture:true,passive:true});document.addEventListener('pointerdown',R.noteWebUiInteraction,true);document.addEventListener('click',R.noteWebUiInteraction,true);document.addEventListener('input',R.noteWebUiInteraction,true);document.addEventListener('change',R.noteWebUiInteraction,true);document.addEventListener('keydown',R.noteWebUiInteraction,true);R.setMutable(false);R.claimWebUiOwnership();
